-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 19:09:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hikers_guide_to_the_galaxy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hikers_guide_to_the_galaxy` ;

-- -----------------------------------------------------
-- Schema hikers_guide_to_the_galaxy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hikers_guide_to_the_galaxy` DEFAULT CHARACTER SET utf8 ;
USE `hikers_guide_to_the_galaxy` ;

-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`parks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`parks` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`parks` (
  `park_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`park_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`trail_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`trail_types` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`trail_types` (
  `type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`trails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`trails` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`trails` (
  `trail_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `difficulty` INT(11) NULL DEFAULT NULL,
  `length` INT(11) NULL DEFAULT NULL,
  `type_id` INT(11) NOT NULL,
  `park_id` INT(11) NOT NULL,
  PRIMARY KEY (`trail_id`, `type_id`, `park_id`),
  INDEX `fk_trails_trail_types1_idx` (`type_id` ASC),
  INDEX `fk_trails_parks1_idx` (`park_id` ASC),
  CONSTRAINT `fk_trails_parks1`
    FOREIGN KEY (`park_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`parks` (`park_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trails_trail_types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`trail_types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`gps_coords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`gps_coords` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`gps_coords` (
  `gps_id` INT(11) NOT NULL AUTO_INCREMENT,
  `point` POINT NULL DEFAULT NULL,
  `trail_id` INT(11) NOT NULL,
  PRIMARY KEY (`gps_id`, `trail_id`),
  INDEX `fk_gps_coords_trails1_idx` (`trail_id` ASC),
  CONSTRAINT `fk_gps_coords_trails1`
    FOREIGN KEY (`trail_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`trails` (`trail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`activities` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`activities` (
  `gps_id` INT(11) NOT NULL,
  `desc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`gps_id`),
  INDEX `fk_activities_gps_coords1_idx` (`gps_id` ASC),
  CONSTRAINT `fk_activities_gps_coords1`
    FOREIGN KEY (`gps_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`gps_coords` (`gps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`trail_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`trail_reviews` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`trail_reviews` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL DEFAULT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`users` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `loc` POINT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`completed_trails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`completed_trails` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`completed_trails` (
  `trail_id` INT(11) NOT NULL,
  `review_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`trail_id`, `user_id`, `review_id`),
  INDEX `fk_completed_trails_trails1_idx` (`trail_id` ASC),
  INDEX `fk_completed_trails_users1_idx` (`user_id` ASC),
  INDEX `fk_completed_trails_reviews1_idx` (`review_id` ASC),
  CONSTRAINT `fk_completed_trails_reviews1`
    FOREIGN KEY (`review_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`trail_reviews` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_completed_trails_trails1`
    FOREIGN KEY (`trail_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`trails` (`trail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_completed_trails_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`geocaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`geocaches` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`geocaches` (
  `gps_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `desc` TEXT NULL DEFAULT NULL,
  `geocachescol` VARCHAR(45) NULL,
  PRIMARY KEY (`gps_id`),
  INDEX `fk_geocaches_gps_coords1_idx` (`gps_id` ASC),
  INDEX `fk_geocaches_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_geocaches_gps_coords1`
    FOREIGN KEY (`gps_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`gps_coords` (`gps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geocaches_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`pictures` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`pictures` (
  `pic_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pic` BLOB NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `gps_id` INT(11) NOT NULL,
  PRIMARY KEY (`pic_id`, `user_id`, `gps_id`),
  INDEX `fk_pictures_users1_idx` (`user_id` ASC),
  INDEX `fk_pictures_gps_coords1_idx` (`gps_id` ASC),
  CONSTRAINT `fk_pictures_gps_coords1`
    FOREIGN KEY (`gps_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`gps_coords` (`gps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pictures_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hikers_guide_to_the_galaxy`.`trail_heads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikers_guide_to_the_galaxy`.`trail_heads` ;

CREATE TABLE IF NOT EXISTS `hikers_guide_to_the_galaxy`.`trail_heads` (
  `trail_id` INT(11) NOT NULL,
  `gps_id` INT(11) NOT NULL,
  PRIMARY KEY (`trail_id`, `gps_id`),
  INDEX `fk_trail_heads_trails_idx` (`trail_id` ASC),
  INDEX `fk_trail_heads_gps_coords1_idx` (`gps_id` ASC),
  CONSTRAINT `fk_trail_heads_gps_coords1`
    FOREIGN KEY (`gps_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`gps_coords` (`gps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trail_heads_trails`
    FOREIGN KEY (`trail_id`)
    REFERENCES `hikers_guide_to_the_galaxy`.`trails` (`trail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `hikers_guide_to_the_galaxy` ;

-- -----------------------------------------------------
-- function get_distance
-- -----------------------------------------------------

USE `hikers_guide_to_the_galaxy`;
DROP function IF EXISTS `hikers_guide_to_the_galaxy`.`get_distance`;

DELIMITER $$
USE `hikers_guide_to_the_galaxy`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `get_distance`(
	pointA point,
    pointB point
) RETURNS float
BEGIN
RETURN DEGREES(ACOS(
          COS(RADIANS(ST_X(pointA))) *
          COS(RADIANS(ST_X(pointB))) *
          COS(RADIANS(ST_Y(pointB)) - RADIANS(ST_Y(pointA))) +
          SIN(RADIANS(ST_X(pointA))) * SIN(RADIANS(ST_X(pointB)))
        )) * 3961;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
